### ISSUE TITLE
Error in LDSearch 

### ISSUE THREAD

**Issue by ypnngaa-py** [ropensci/rsnps#32] opened 2016-11-17 11:06 UTC
I tried an example:
LDSearch('rs113196607')
Querying SNAP...
Error in out$SNP : $ operator is invalid for atomic vectors

Any solutions?

Thanks!

**Comment by haozhu233** [comment] 2016-11-17 14:16
Hi, @ypnngaa-py,

I just tried it on my machine and I cannot reproduce this error message. Did you update to the latest version of rsnps on github?

**Comment by sckott** [comment] 2016-11-17 22:03
@ypnngaa-py please share your `sessionInfo()`

**Comment by ypnngaa-py** [comment] 2016-11-17 22:20
R version 3.2.2 (2015-08-14)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: OS X 10.12.1 (unknown)

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] rsnps_0.1.6

loaded via a namespace (and not attached):
 [1] httr_1.2.1     magrittr_1.5   plyr_1.8.4     R6_2.2.0       tools_3.2.2   
 [6] RCurl_1.95-4.8 Rcpp_0.12.7    stringi_1.1.2  stringr_1.1.0  jsonlite_1.1  
[11] bitops_1.0-6   XML_3.98-1.5

**Comment by ypnngaa-py** [comment] 2016-11-17 22:21
@haozhu233 I installed by `install.packages("rsnps")`

**Comment by sckott** [comment] 2016-11-18 19:44
@ypnngaa-py sorry about that, that does appear to be a bug in the CRAN version. 

for now, install the dev version like `devtools::install_github("ropensci/rsnps")`

**Comment by sckott** [comment] 2016-11-18 22:59
this is already fixed in current version on `master`, closing

**Closed by sckott** 2016-11-18 22:59 UTC
Labels: Bug
